#!/bin/sh

echo "HELIOS Backend Service"
echo "Copyright (C) 2017, Devin Butterfield."
echo ""
export ERL_LIBS=/opt/k6drs/helios_backend
run_erl -daemon /opt/k6drs/helios_backend/pipe /opt/k6drs/helios_backend/log "exec erl -mnesia dir '\"/opt/k6drs/helios_backend/db\"' -sname backend -setcookie k6drs -pa /opt/k6drs/helios_backend/ebin -pa /opt/k6drs/helios_backend/deps/*/ebin -config /opt/k6drs/helios_backend/priv/app.config -s backend"